github:
  token: "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"
  organization: "mosmatan"
  repository: "PR_Tests"
  api_base_url: "https://api.github.com"

data:
  raw_dir_path: "../data/raw"
  processed_dir_path: "../data/processed"

output:
  report_dir_path: "../output/reports"

tests:
  github:
    token: "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"
    organization: "mosmatan"
    repository: "PR_Tests"
    api_base_url: "https://api.github.com"
    pr_number : 1

  data:
    raw_dir_path: "/data/raw"
    processed_dir_path: "/data/processed"

  output:
    report_dir_path: "/output/reports"