github:
  token: "<YOUR GITHUB TOKEN>"
  organization: "mosmatan"
  repository: "PR_Tests"
  api_base_url: "https://api.github.com"

data:
  raw_dir_path: "../data/raw"
  processed_dir_path: "../data/processed"

output:
  report_dir_path: "../output/reports"

tests:
  github:
    token: "<YOUR GITHUB TOKEN>"
    organization: "mosmatan"
    repository: "PR_Tests"
    api_base_url: "https://api.github.com"
    pr_number : 1

  data:
    raw_dir_path: "/data/raw"
    processed_dir_path: "/data/processed"

  output:
    report_dir_path: "/output/reports"